// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCn0eqwMwiFywQhrX8hiaaSdrX7NNss7Q',
    appId: '1:495117466135:web:a4d2f095c21335ba2aba52',
    messagingSenderId: '495117466135',
    projectId: 'gas-master',
    authDomain: 'gas-master.firebaseapp.com',
    storageBucket: 'gas-master.appspot.com',
    measurementId: 'G-033DNLL53R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqBfE2Yfb37d1qFAPTGrB8n2kWuwm3AsU',
    appId: '1:495117466135:android:f17ff9f91a7bf9852aba52',
    messagingSenderId: '495117466135',
    projectId: 'gas-master',
    storageBucket: 'gas-master.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-5vokTN2XCeg3Z3Za9z6zfQHX6n2I8WU',
    appId: '1:495117466135:ios:152b6a9bf626a1972aba52',
    messagingSenderId: '495117466135',
    projectId: 'gas-master',
    storageBucket: 'gas-master.appspot.com',
    iosBundleId: 'com.example.gasMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-5vokTN2XCeg3Z3Za9z6zfQHX6n2I8WU',
    appId: '1:495117466135:ios:793d62a37ec5d3382aba52',
    messagingSenderId: '495117466135',
    projectId: 'gas-master',
    storageBucket: 'gas-master.appspot.com',
    iosBundleId: 'com.example.gasMaster.RunnerTests',
  );
}
